<?php

/**
 * @file
 *
 * This module allows admins to set recurrent announcements for nodes to send
 * to specified email addresses.
 */

/**
 * Implentation of hook_menu()
 */
function node_announce_menu() {
  $items = array();
  $items['admin/settings/node_announce'] = array(
    'title' => t('Node Announcements'),
    'description' => t('Configure node announcements'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_announce_form_list'),
    'access arguments' => array('administer node announcements'),
    'file' => 'node_announce.admin.inc',
  );

  $items['admin/settings/node_announce/list'] = array(
    'title' => t('List'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  $items['admin/settings/node_announce/add'] = array(
    'title' => t('Add Announce'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_announce_form'),
    'access arguments' => array('administer node announcements'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'node_announce.admin.inc',
  );

  $items['admin/settings/node_announce/%/edit'] = array(
    'type' => MENU_CALLBACK,
    'title' => t('BAR'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('node_announce_form', 3),
    'access arguments' => array('administer node announcements'),
    'file' => 'node_announce.admin.inc',
  );


  $items['admin/settings/node_announce/%/preview'] = array(
    'type' => MENU_CALLBACK,
    'title' => t('FOOOOOO'),
    'page callback' => 'node_announce_preview',
    'page arguments' => array(3),
    'access arguments' => array('administer node announcements'),
    'file' => 'node_announce.admin.inc',
  );
  return $items;
}


/**
 * Implementation of hook_perm()
 */
function node_announce_perm() {
  return array('administer node announcements');
}

/**
 * Implementation of hook_nodeapi()
 */
function node_announce_nodeapi(&$node, $op, $a3, $a4) {
  switch($op) {
    case 'delete':
      node_announce_delete_records($node->nid);
      break;
      // TODO: should we indicate that announcements will be sent out to admins?
  }
}


/**
 *  Implementation of hook_cron().
 *
 *  Go through all the announcements and set
 */
function node_announce_cron() {
  _node_announce_load_api();
  node_announce_process();
}

/**
 * Load API calls, which gives us access to DB and permissions checks
 */
function _node_announce_load_api() {
  require_once('./' . drupal_get_path('module', 'node_announce') . '/node_announce_api.inc');
}

function node_announce_theme() {
  $path = drupal_get_path('module', 'node_announce');
  $base = array(
    'path' => "$path/theme"
  );

  // TODO: get forms in here as well, though I was having an issue getting
  // them to take parameters as well as the form parameters
  $themes = array(
    'node_announce_list' => $base + array(
      'template' => 'node-announce-list',
      'arguments' => array('announces' => array())
    ),
    'node_announce_preview' => $base + array(
      'template' => 'node-announce-preview',
      'arguments' => array('announce' => NULL, 'node' => NULL)
    ),
  );
  return $themes;
}


/**
 * TODO: make this strip out all the html formatting for plain sending
 */

function node_announce_mail($key, &$message, $params) {
  if ($key == 'node_announce') {
    $node = $params['node'];
    $ann = $params['announce'];

    $message['to'] = $ann->email_to;
    $message['from'] = $ann->email_from;
    $message['subject'] = token_replace($ann->subject, 'node', $node);
    $message['body'] = token_replace($ann->message, 'node', $node);
  }
}

/***
 *
 */

function node_announce_process() {
  drupal_set_message("Running node_announce cron job");

  $announces = node_announce_list();

  drupal_set_message("Got the following announces: " . print_r($announces, TRUE));

  foreach ($announces as $ann) {
    $nodes = node_announce_applicable_nodes($ann);

    drupal_set_message("Announce " . $ann->id . " got the following nodes: " . print_r($nodes, TRUE));

    foreach ($nodes as $node) {
      if (! node_announce_already_announced($ann, $node)) {
        node_announce_send_announce($ann, $node);
        node_announce_record_send($ann->id, $node->nid);
      }
    }
  }
}


function node_announce_send_announce($ann, $node) {
  $result = mimemail(
    $ann->email_from,
    $ann->email_to,
    token_replace($ann->subject, 'node', $node),
    token_replace($ann->message, 'node', $node),
    NULL, /* plain text only */
    array(),  /* additional headers */
    NULL, /* custom plain text */
    array(), /* attachments .... maybe put ical here later? */
    'node_announce'
  );

  /*** TODO: gracefully work without mimemail
  $params = array('announce' => $ann, 'node' => $node);
  $result = drupal_mail('node_announce', 'node_announce', $ann->email_to, language_default(), $params); */

}